### PR TITLE
added taxila scrapers

### PR DESCRIPTION
**Pull request by mikesndrs**

### CODE REVIEW

**Review by fbacall — CHANGES_REQUESTED** [review]
Thanks!

Regarding the CodeQL warnings, check this commit I just pushed: https://github.com/ElixirTeSS/TeSS/commit/77a024c5658fdc201cc1386f0d8d185469f54a05

If you replace all the `URI.open` calls with `open_url` it should be good (you can pass `raise: true` if you want it to raise on non-200 responses).

Can you also add some basic tests that covers this code? For example I can see that there are calls to `Sentry.capture_exception` which would error since `sentry` is not a dependency in this repo

**Comment by mikesndrs** [comment]
Some of the sites have no proper access to past events (or at least I cannot find it), so I have no good targets for unit tests. Because of that the draft tests for those scrapers are a full scrape after which it is checked whether any events are added. This does not check if the data is properly scraped and it takes too long for CI (especially when the scrapers use sleep). What would be a good way to solve this problem properly?

**Comment by fbacall** [comment]
So the current ingestors are tested by intercepting the URL being scraped, and serving a static file instead (using webmock)*:
https://github.com/ElixirTeSS/TeSS/blob/31fe184a2560c5aa07a1a9df2a3bc1a3dae850cf/test/test_helper.rb#L176-L224

with the content of those URLs being stored here:
https://github.com/ElixirTeSS/TeSS/tree/master/test/fixtures/files/ingestion

The tests should not make actual "live" HTTP requests, as these will probably break if there are network issues, or if the site changes etc. . They're just to ensure the scraping code is covered for regression testing.

To avoid delays with `sleep` etc. you could skip them if `Rails.env.test?` or something (after the code is changed to serve mock responses).

* If I had written the original tests though, I would have used `VCR` which captures the first real HTTP request/response, and then replays it on subsequent accesses. Basically the same thing, but less manual effort. It is used here:
https://github.com/ElixirTeSS/TeSS/blob/7fd07ae3c9b5584a34b7f9d69c8802504389724d/test/unit/fairsharing/client_test.rb#L151-L161

with the "cassettes" stored here: https://github.com/ElixirTeSS/TeSS/tree/7fd07ae3c9b5584a34b7f9d69c8802504389724d/test/vcr_cassettes/fairsharing

It's up to you which approach you use.

**Comment by fbacall** [comment]
For the Leiden and DANS scrapers it looks like it is scraping the same page (or at least the same events) 4 times

For the OSCM scraper, the events have the following error:
```Event types contained invalid terms: FAIR coffee```
as that term is not in `config/dictionaries/event_types.yml`

**Review by fbacall — APPROVED** [review]
Great, thanks!

**Pull request merged**
