### PR TITLE
use funders list to draw supported by footer segment

### PR DESCRIPTION
**Pull request by DaanVanVugt**
**Summary of changes**
Instead of hardcoding the supported-by page it is now set based on the funder list.

**Motivation and context**
This removes a hardcoded set of information and makes the funders list easier to update.

**Checklist**

- [x] I have read and followed the [CONTRIBUTING](https://github.com/ElixirTeSS/TeSS/blob/master/CONTRIBUTING.md) guide.
- [x] I confirm that I have the authority necessary to make this contribution on behalf of its copyright owner and agree
  to license it to the TeSS codebase under the 
  [BSD license](https://github.com/ElixirTeSS/TeSS/blob/master/LICENSE).

### CODE REVIEW

**Comment by DaanVanVugt** [comment]
There is one more thing to do in this file, the funding statement is hidden somehow (and should be loaded from a locale file, so we can tweak it for Taxila)

**Comment by fbacall** [comment]
Looks good. Maybe just a boolean to show/hide the EU notice and entry in locale to change the text?

**Review by fbacall — CHANGES_REQUESTED** [review]

**Review by fbacall — CHANGES_REQUESTED** [review]
Can you revert the `Gemfile.lock` change and remove `tess.crontab`?

Otherwise looks good.

**Review by fbacall — APPROVED** [review]
Thanks!

**Pull request merged**
